enabled:
  csharp:
    docker: mono:latest
    workdir: /opt/build
    build_command: |
      csc #{code} -out:#{build_target} #{references} -errorlog:error.log
  cpp_windows:
    docker: dockcross/windows-static-x64
    workdir: /opt/build
    build_command: |
      /bin/bash -c "$CXX -x c++ -o #{build_target} #{code} > error.log 2>&1"
